fail_fast: true
default_stages: [commit, push]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-case-conflict
      - id: name-tests-test
      - id: mixed-line-ending
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
  - repo: https://github.com/hadialqattan/pycln
    rev: v2.4.0
    hooks:
    - id: pycln
      args: [--config=pyproject.toml]
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.2
    hooks:
    -   id: pyupgrade
        args: [--py310-plus]
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)
  - repo: https://github.com/pycqa/flake8
    rev: '7.0.0'
    hooks:
    -   id: flake8
        args: [--max-line-length=88, --extend-ignore=E203, --extend-ignore=E501, --extend-ignore=W503]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.9.0'
    hooks:
    -   id: mypy
        args: [--ignore-missing-imports, --show-error-codes, --pretty]
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest
        language: python
        types: [python]
        pass_filenames: false
        stages: [commit, push]
        always_run: true
        verbose: true
        require_serial: true
        additional_dependencies: [pytest]
        description: Run pytest
        files: ^tests/.*\.py$
        exclude: ^tests/conftest\.py$
        exclude_types: [yaml, toml, json]
      - id: pytest-cov
        name: pytest-cov
        entry: pytest
        language: python
        types: [python]
        pass_filenames: false
        stages: [commit, push]
        args: [--cov=data_generators, --cov-report=term-missing]
        always_run: true
        verbose: true
        require_serial: true
        additional_dependencies: [pytest, pytest-cov]
        description: Run pytest with coverage
        files: ^tests/.*\.py$
        exclude: |-
          ^tests/conftest\.py$
          ^tests/test_.*\.py$
        exclude_types: [yaml, toml, json]
